### ISSUE TITLE
Setup CI/CD Tooling

### ISSUE THREAD

**Issue by Klaus112** [Klaus112/micro-notes#3]
- [ ] Choose a tool (some options: CircleCI, GoCD, ArgoCD)
- [ ] Write pipeline for it
- [ ] Deploy microservice to cluster
