### ISSUE TITLE
TO DO Microservice

### ISSUE THREAD

**Issue by Klaus112** [Klaus112/micro-notes#4]
- [ ] Create TO-DOs
- [ ] List TO-Dos with different filters (think about filtering approach)
- [ ] Removal of TO-DOs
- [ ] Update of TO-DOs
